mysite/common/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', views.LogIn, name='login'),
    path('logout/', views.LogOut, name='logout'),
    path('signup/', views.SignUp, name='signup'),
    path('subscribe/', views.Subscribe, name='subscribe'),
    path('subscribe_book/', views.subscribe_book, name='subscribe_book'),
    path('subscribe_book/book2/', views.subscribe_book2, name='subscribe_book2'),
    path('subscribe_book/book2/success/', views.subscribe_success, name='subscribe_success'),
]

mysite/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('detail_news/', views.detail_news, name='detail_news'),
    path('detail_books/', views.detail_books, name='detail_books'),
]

mysite/pagepalette/urls.py
from django.urls import include, path
from main import views

urlpatterns = [
    path('main/', include('main.urls')),
    path('common/', include('common.urls')),
    path('', views.main, name='main'),
]

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>페이지 팔레트</title>
<!--    <link rel=“stylesheet” href=“./index.css”>-->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Gothic+Coding&family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Gothic&family=Nanum+Gothic+Coding&display=swap');
        .dongle{
            font-family: 'Dongle', sans-serif;
        }
        .gothic{
            font-family: 'Nanum Gothic', sans-serif;
        }
        .coding{
            font-family: 'Nanum Gothic Coding', monospace;
        }
    </style>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}


<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

mysite/templates/detail.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'detail.css' %}">
    <!--230705 1110 추가-->

    <title>페이지 팔레트</title>
<!--    <link rel="stylesheet" href="./index.css">-->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Gothic+Coding&family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Gothic&family=Nanum+Gothic+Coding&display=swap');
        .dongle{
            font-family: 'Dongle', sans-serif;
        }
        .gothic{
            font-family: 'Nanum Gothic', sans-serif;
        }
        .coding{
            font-family: 'Nanum Gothic Coding', monospace;
        }
    </style>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}


<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

mysite/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

mysite/templates/navbar.html
{% load static %}

<header>
    <div class="container">
        <div class="left">
            <a href="{% url 'main:main' %}"><img src="{% static 'images/icons/long_logo.png' %}" alt="logo" style="width: 238px; height: 40px"></a>
        </div>

        <nav>
            <ul>
                {% if request.session.user_id %}
                <li>
                    <a href="{% url 'common:subscribe' %}"><button class="coding">구독하기</button></a>
                </li>
                <li>
                    <a href="{% url 'common:logout' %}"><button class="coding">로그아웃</button></a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'common:login' %}"><button class="coding">구독하기</button></a>
                </li>
                <li>
                    <a href="{% url 'common:login' %}"><button class="coding">로그인</button></a> / <a href="{% url 'common:signup' %}"><button class="coding">회원가입</button></a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

mysite/templates/subscribe_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'subscribe_book.css' %}">
    <!--230705 1110 추가-->

    <title>구독 상세</title>
<!--    <link rel="stylesheet" href="./index.css">-->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Gothic+Coding&family=Nanum+Pen+Script&family=Poppins:wght@400;700&family=Varela+Round&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Dongle&family=Nanum+Gothic&family=Nanum+Gothic+Coding&display=swap');
        .dongle{
            font-family: 'Dongle', sans-serif;
        }
        .gothic{
            font-family: 'Nanum Gothic', sans-serif;
        }
        .coding{
            font-family: 'Nanum Gothic Coding', monospace;
        }
    </style>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}


<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>