mysite/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('detail_news/', views.detail_news, name='detail_news'),
    path('detail_books/', views.detail_books, name='detail_books'),
]

mysite/pagepalette/urls.py
from django.urls import include, path
from main import views

urlpatterns = [
    path('main/', include('main.urls')),
    path('common/', include('common.urls')),
    path('', views.main, name='main'),
]

mysite/main/models.py
from django.db import models

# Create your models here.

mysite/main/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def main(request):
    return render(request, 'main/main.html')
        # HttpResponse('main page')

def detail_news(request):
    return render(request, 'main/detail_news.html')

def detail_books(request):
    return render(request, 'main/detail_books.html')

mysite/templates/main/detail_books.html
{% extends 'detail.html' %}
{% block content %}
<main>
      <div class="contents-container">

          <div class="text-container">
              <h3 class="gothic" style="line-height: 30px">이제 더 이상 무슨 책 읽을지 고민하지 마세요 !<br>매주 금요일마다 나만을 위한 책 추천 리스트를 받아보세요.</h3>
          </div>

          <div class="bookmark-container">
              <a href="{% url 'main:detail_news' %}" class="detail_news_url"><button class="coding">뉴스</button></a>
          </div>

          <div class="image-container">
              <div class="grid-item-mainImg">
                  <img src="../../static/images/book_rcmd.png" alt="" style="width: 230px; height: 420px; border: 1px solid black">
              </div>

              <div class="grid-item-text" style="line-height: 20px;">
                  <p class="gothic" style="font-weight: bold; color: darkgreen">나를 위한 새로운 책 추천을 받아보세요! AI가 당신에게 어울리는 책을 추천해드려요!</p>
                  <p class="gothic" style="font-weight: bold">먼저 좋아하는 책 장르를 선택하면, 선택한 장르에 맞는 12권의 책이 나타납니다.</p>
                  <p class="gothic" style="font-weight: bold">12권 중에서 맘에 드는 책을 선택해주세요!</p>
                  <br>
                  <p class="gothic" style="font-weight: bold; color: darkgreen">선정된 책은 금요일마다 4권씩, 뉴스와 같이 이메일로 보내드릴게요.</p>
                  <p class="gothic" style="font-weight: bold">이제 매주 금요일, 새로운 책을 발견하고 독서의 즐거움을 경험해보세요.</p>
                  <p class="gothic" style="font-weight: bold">오직 당신만을 위한 도서 추천 서비스가 여러분을 기다리고 있습니다.</p>
              </div>

              <div class="grid-item-subImg" style="display: flex; flex-direction: row; justify-content: space-between;">
                  <img src="../../static/images/select.png" alt="" style="width: 210px; height: 220px; border: 1px solid black; box-shadow: 3px 3px 3px 0 rgba(0, 0, 0, 0.3);">

                  <img src="../../static/images/twelve.png" alt="" style="width: 425px; height: 220px; border: 1px solid black; box-shadow: 3px 3px 3px 0 rgba(0, 0, 0, 0.3);">
              </div>

              <div class="grid-item-exMsg1">
                  <p style="color: gray; font-size: small">(예시 이미지)</p>
              </div>

              <div class="grid-item-exMsg2">
                  <p style="color: gray; font-size: small">(예시 이미지)</p>
              </div>
          </div>

      </div>
</main>
{% endblock %}

mysite/templates/main/detail_news.html
{% extends 'detail.html' %}
{% block content %}
<main>
      <div class="contents-container">
          <div class="text-container">
              <h3 class="gothic" style="line-height: 30px">PagePalette의 뉴스 클리핑 서비스로 <br> 당신은 더 이상 언론사가 정해주는 헤드라인에만 의존하지 않아도 됩니다!</h3>
          </div>

          <div class="bookmark-container">
              <a href="{% url 'main:detail_books' %}" class="detail_books_url"><button class="coding">도서</button></a>
          </div>

          <div class="image-container">
              <div class="grid-item-mainImg">
                  <img src="../../static/images/news_form_LG.png" alt="" style="width: 230px; height: 420px; border: 1px solid black">
              </div>

              <div class="grid-item-text" style="line-height: 20px;">
                  <p class="gothic" style="font-weight: bold; color: darkgreen">단순히 자극적인 기사, 조회수가 많은 기사만을 보내드리지 않습니다!</p>
                  <p class="gothic" style="font-weight: bold">AI가 최근 24시간 동안 발생한 다양한 주제의 뉴스를 분석하여 가장 핵심적인 주제와<br> 관련된 기사를 추려서 그날의 진짜 트렌드를 파악할 수 있습니다!</p>
                  <br>
                  <p class="gothic" style="font-weight: bold; color: darkgreen">뉴스 클리핑 메일은 원하는 시간에 받아볼 수 있습니다!</p>
                  <p class="gothic" style="font-weight: bold">받고 싶은 시간대를 지정하면, 그 시간에 핵심적인 주제와 뉴스를 보내드립니다!</p>
                  <br>
                  <p class="gothic" style="font-weight: bold; color: darkgreen">바쁜 당신을 위해 AI가 기사 요약도 해줘요!</p>
                  <p class="gothic" style="font-weight: bold">링크를 열고 들어가지 않아도 간단하게 메일에서 요약만 읽어볼 수 있어요!</p>
              </div>

              <div class="grid-item-subImg">
                  <img src="../../static/images/LDA.png" alt="" style="width: 500px; height: 210px; border: 1px solid black; box-shadow: 3px 3px 3px 0 rgba(0, 0, 0, 0.3);">
              </div>

              <div class="grid-item-exMsg1">
                  <p style="color: gray; font-size: small">(예시 이미지)</p>
              </div>

              <div class="grid-item-exMsg2">
                  <p style="color: gray; font-size: small">(예시 이미지)</p>
              </div>
          </div>
      </div>
</main>
{% endblock %}

mysite/templates/main/main.html
{% extends 'base.html' %}
{% block content %}
    <main id="main">
        <div class="container">
            <h2 style="font-size: 40px; text-shadow: 1px 1px 1px #a2a2a2;" class="coding">매일 <span style="color: darkgreen" class="coding">메일</span> 트렌드 키워드를 확인하세요</h2>
            <p class="coding" style="font-weight: bold;">원하신다면, 맞춤 도서 추천도 해드려요</p>
            <!-- <a href="www.google.com"><img src="./images/buttons/red.png" alt="구독하기"></a>
            <a href="www.google.com"><img src="./images/buttons/blue.png" alt="구독하기"></a> -->

            <a href="{% url 'main:detail_news' %}" style="padding-right: 50px"><button class="coding">뉴스</button></a>
            <a href="{% url 'main:detail_books' %}"><button class="coding">도서 큐레이션</button></a>
            <!-- <button class="mouse"><img src="./images/buttons/blue.png" alt=""></button> -->
        </div>
    </main>
{% endblock %}